//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerDB
    {
        public string Name { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Branch_Name { get; set; }
    }
}
