//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsedCarsTable
    {
        public int Id { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int ManufecturingYear { get; set; }
        public int Milage { get; set; }
        public string Type { get; set; }
        public string Colour { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public string SellerName { get; set; }
        public string SellerContact { get; set; }
    }
}
